import * as fs from 'fs';
import crypto from 'crypto';
import { ccc } from '@ckb-ccc/core';
import accountConfig from '../../account/account.json';
import { fiberAccountIndex, fiberNodePaths, UDT_ISSUER_ACCOUNT_INDEX } from './paths';
import { readSettings, Settings } from '../cfg/setting';

export interface BuiltinAccount {
  privkey: string;
  pubkey: string;
  lockScript: {
    codeHash: string;
    hashType: string;
    args: string;
  };
  address: string;
  args: string;
}

const accounts = accountConfig as unknown as BuiltinAccount[];

export function getBuiltinAccount(index: number): BuiltinAccount {
  const account = accounts[index];
  if (!account) {
    throw new Error(`Built-in account #${index} does not exist (account.json has ${accounts.length} accounts).`);
  }
  return account;
}

// Node N uses CKB account N+2; accounts 3-18 are reserved for Fiber nodes.
export function fiberNodeAccount(nodeId: number): BuiltinAccount {
  return getBuiltinAccount(fiberAccountIndex(nodeId));
}

// Account 19 deploys contracts and issues the sUDT/xUDT used for testing.
export function udtIssuerAccount(): BuiltinAccount {
  return getBuiltinAccount(UDT_ISSUER_ACCOUNT_INDEX);
}

export function udtIssuerLockHash(): string {
  const issuer = udtIssuerAccount();
  return ccc.Script.from(issuer.lockScript as ccc.ScriptLike).hash();
}

// Derive the compressed secp256k1 public key of a raw 32-byte secret, the
// format FNN reports as node_info.pubkey (hex, no 0x prefix).
export function fiberPublicKeyFromSecret(secret: Buffer): string {
  const signer = new ccc.SignerCkbPrivateKey({} as never, `0x${secret.toString('hex')}` as `0x${string}`);
  return signer.publicKey.slice(2).toLowerCase();
}

export function readFiberNodeSecretKey(nodeId: number, settings: Settings = readSettings()): Buffer | null {
  const skFile = fiberNodePaths(nodeId, settings).fiberSkFile;
  try {
    const data = fs.readFileSync(skFile);
    return data.length >= 32 ? data.subarray(0, 32) : null;
  } catch {
    return null;
  }
}

function writePrivateFile(file: string, content: string) {
  fs.writeFileSync(file, content, { mode: 0o600 });
  try {
    fs.chmodSync(file, 0o600);
  } catch {
    // Windows has no POSIX modes; the file inherits directory ACLs.
  }
}

/**
 * Create the node directory layout and its CKB key material. The CKB secret
 * key is written as plain hex (FNN encrypts it in place on first start,
 * using the per-node password passed via FIBER_SECRET_KEY_PASSWORD). The
 * Fiber network identity key (fiber/sk) is generated by FNN itself on first
 * start and must never be overwritten here.
 *
 * Existing nodes keep their key and password; a node directory with missing
 * key material is an error, never silently re-created (the on-chain account
 * and any channels are tied to the original keys).
 */
export function ensureNodeKeyMaterial(nodeId: number, settings: Settings = readSettings()): { created: boolean } {
  const paths = fiberNodePaths(nodeId, settings);
  const keyExists = fs.existsSync(paths.ckbKeyFile);
  const passwordExists = fs.existsSync(paths.passwordFile);
  if (keyExists && passwordExists) {
    return { created: false };
  }
  if (keyExists !== passwordExists) {
    const missing = keyExists ? paths.passwordFile : paths.ckbKeyFile;
    throw new Error(
      `Fiber node ${nodeId} has incomplete key material: ${missing} is missing. ` +
        'The CKB key and its password must both come from the same provisioning; ' +
        'restore the file or remove the node directory and start again.',
    );
  }

  fs.mkdirSync(paths.ckbDir, { recursive: true });
  fs.mkdirSync(paths.fiberDir, { recursive: true });
  const account = fiberNodeAccount(nodeId);
  writePrivateFile(paths.ckbKeyFile, account.privkey.replace(/^0x/, ''));
  writePrivateFile(paths.passwordFile, crypto.randomBytes(24).toString('base64'));
  return { created: true };
}

export function readNodePassword(nodeId: number, settings: Settings = readSettings()): string {
  const passwordFile = fiberNodePaths(nodeId, settings).passwordFile;
  try {
    return fs.readFileSync(passwordFile, 'utf8').trim();
  } catch (error) {
    throw new Error(`Failed to read the password of fiber node ${nodeId}: ${(error as Error).message}`);
  }
}
