import * as fs from 'fs';
import * as path from 'path';
import { packageRootPath, readSettings, Settings } from '../cfg/setting';
import { isFolderExists } from '../util/fs';

// Directory layout of a Fiber devnet environment (see docs/fiber.md):
//
//   <offckb data>/devnet/fiber/
//   ├── nodes.yml            node list and per-node FNN config overrides
//   ├── runtime.json         current manager process and node addresses
//   ├── logs/                fiber start --daemon manager log + pid
//   └── nodes/<id>/
//       ├── config.yml       generated on every start, do not hand-edit
//       ├── ckb/key          CKB secret key (FNN encrypts it on first start)
//       ├── fiber/sk         Fiber network identity key, generated by FNN
//       ├── fiber/store/     FNN database
//       ├── fnn.log          node stdout/stderr
//       └── password         random key-encryption password for this node
//
// The environment lock lives next to the devnet directory (not inside it) so
// `offckb clean`/`fiber clean` can hold it while deleting the whole tree.

export const FIBER_DIR_NAME = 'fiber';
export const NODES_YML_FILE = 'nodes.yml';
export const RUNTIME_JSON_FILE = 'runtime.json';
export const FIBER_LOGS_DIR = 'logs';
export const FIBER_DAEMON_LOG_FILE = 'daemon.log';
export const FIBER_DAEMON_PID_FILE = 'daemon.pid';
export const ENV_LOCK_FILE = '.offckb-devnet.lock';
export const NODE_CONFIG_FILE = 'config.yml';
export const NODE_LOG_FILE = 'fnn.log';
export const NODE_PASSWORD_FILE = 'password';
export const NODE_CKB_DIR = 'ckb';
export const NODE_CKB_KEY_FILE = 'key';
export const NODE_FIBER_DIR = 'fiber';
export const NODE_FIBER_SK_FILE = 'sk';
export const NODE_FIBER_STORE_DIR = 'store';
export const ROCKSDB_LOCK_FILE = 'LOCK';

export const MIN_FIBER_NODES = 1;
export const MAX_FIBER_NODES = 16;
export const DEFAULT_FIBER_NODES = 2;

// Node N uses CKB account N+2 (accounts 3-18 are reserved for Fiber; account
// 19 deploys contracts and issues the test UDTs), RPC port 21713+N and P2P
// port 8343+N.
export const FIBER_ACCOUNT_OFFSET = 2;
export const FIBER_RPC_PORT_BASE = 21713;
export const FIBER_P2P_PORT_BASE = 8343;
export const UDT_ISSUER_ACCOUNT_INDEX = 19;

export function fiberRootPath(settings: Settings = readSettings()): string {
  return path.join(settings.devnet.configPath, FIBER_DIR_NAME);
}

export function nodesYmlPath(settings: Settings = readSettings()): string {
  return path.join(fiberRootPath(settings), NODES_YML_FILE);
}

export function runtimeJsonPath(settings: Settings = readSettings()): string {
  return path.join(fiberRootPath(settings), RUNTIME_JSON_FILE);
}

export function fiberLogsPath(settings: Settings = readSettings()): string {
  return path.join(fiberRootPath(settings), FIBER_LOGS_DIR);
}

export function fiberDaemonPaths(settings: Settings = readSettings()) {
  const logDir = fiberLogsPath(settings);
  return {
    logDir,
    logFile: path.join(logDir, FIBER_DAEMON_LOG_FILE),
    pidFile: path.join(logDir, FIBER_DAEMON_PID_FILE),
  };
}

export function envLockPath(settings: Settings = readSettings()): string {
  // Sibling of the devnet directory: <data>/.offckb-devnet.lock
  return path.join(path.dirname(settings.devnet.configPath), ENV_LOCK_FILE);
}

export function fiberNodeDir(id: number, settings: Settings = readSettings()): string {
  return path.join(fiberRootPath(settings), 'nodes', String(id));
}

// Ids of the node directories present under <fiber>/nodes, in numeric order.
export function fiberNodeIds(settings: Settings = readSettings()): number[] {
  const nodesDir = path.join(fiberRootPath(settings), 'nodes');
  if (!isFolderExists(nodesDir)) return [];
  return fs
    .readdirSync(nodesDir)
    .filter((entry) => /^\d+$/.test(entry))
    .map((entry) => Number(entry))
    .sort((a, b) => a - b);
}

export function fiberNodePaths(id: number, settings: Settings = readSettings()) {
  const dir = fiberNodeDir(id, settings);
  return {
    dir,
    configFile: path.join(dir, NODE_CONFIG_FILE),
    logFile: path.join(dir, NODE_LOG_FILE),
    passwordFile: path.join(dir, NODE_PASSWORD_FILE),
    ckbDir: path.join(dir, NODE_CKB_DIR),
    ckbKeyFile: path.join(dir, NODE_CKB_DIR, NODE_CKB_KEY_FILE),
    fiberDir: path.join(dir, NODE_FIBER_DIR),
    fiberSkFile: path.join(dir, NODE_FIBER_DIR, NODE_FIBER_SK_FILE),
    fiberStoreDir: path.join(dir, NODE_FIBER_DIR, NODE_FIBER_STORE_DIR),
    storeLockFile: path.join(dir, NODE_FIBER_DIR, NODE_FIBER_STORE_DIR, ROCKSDB_LOCK_FILE),
  };
}

export function fiberAccountIndex(nodeId: number): number {
  return nodeId + FIBER_ACCOUNT_OFFSET;
}

export function fiberRpcPort(nodeId: number): number {
  return FIBER_RPC_PORT_BASE + nodeId;
}

export function fiberP2pPort(nodeId: number): number {
  return FIBER_P2P_PORT_BASE + nodeId;
}

export function fiberRpcUrl(nodeId: number): string {
  return `http://127.0.0.1:${fiberRpcPort(nodeId)}`;
}

export function fiberP2pAddr(nodeId: number): string {
  return `/ip4/127.0.0.1/tcp/${fiberP2pPort(nodeId)}`;
}

// Fallback FNN testnet config shipped with offckb, used when a local FNN
// binary has no sibling config/testnet/config.yml. The Makefile copies it
// from the pinned ckb/fiber submodule into the devnet specs.
export function bundledFiberTestnetConfigPath(): string {
  return path.join(packageRootPath, 'ckb', 'devnet', 'specs', 'fiber', 'testnet-config.yml');
}
